[package]
name = "reify_types"
version.workspace = true
edition.workspace = true
readme = "../README.md"

[dependencies]
syn.workspace = true
reify_types_macro.workspace = true

[dev-dependencies]
trybuild.workspace = true
